<?php
/**
 * Created by PhpStorm.
 * User: Okhamafe Emmanuel
 * Date: 7/8/2019
 * Time: 4:04 AM
 */
?>
<div class="contact-us-page">
<div class="row form-contact">
    <div class="col-lg-12 col-md-12">
        <form class="form contact"
            action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
                id="contact-form"
                method="post"
                data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
                data-mage-init='{"validation":{}}'>
                <fieldset class="fieldset">
                    <div class="title-bonus-page">
                        <h2><?php /* @escapeNotVerified */ echo __('Request A Quote') ?></h2>
                    </div>
                    <div class="left-input">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-xs-12">
                                <div class="field name required">
                                    <div class="control">
                                        <input placeholder="<?php echo __('First Name*')?>" name="first_name" id="first_name" title="<?php /* @escapeNotVerified */ echo __('First Name') ?>"  class="input-text" type="text" data-validate="{required:true, maxlength:50}"/>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-xs-12">
                                <div class="field name required">
                                    <div class="control">
                                        <input placeholder="<?php echo __('Last Name*')?>" name="last_name" id="last_name" title="<?php /* @escapeNotVerified */ echo __('Last Name') ?>" class="input-text" type="text" data-validate="{required:true, maxlength:50}"/>
                                    </div>
                                </div>
                            </div>
                        </div>


                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-xs-12">
                                <div class="field telephone required">
                                    <div class="control">
                                        <input placeholder="<?php echo __('Phone*')?>" name="phone_number" id="phone_number" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="" class="input-text" type="text" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-xs-12">
                                <div class="field email required">
                                    <div class="control">
                                        <input placeholder="<?php echo __('Email*')?>" name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="field comment required">
                        <div class="control">
                            <textarea placeholder="<?php echo __('Message*')?>" name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
                        </div>
                    </div>
                    <?= $block->getBlockHtml('formkey') ?>
                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary">
                        <input type="hidden" name="hideit" id="hideit" value="" />
                        <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Send Your Message') ?>" class="action submit primary">
                            <span><?php /* @escapeNotVerified */ echo __('Request Quote') ?></span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    require([
        'jquery',
        'mage/mage'
    ], function ($) {
        var dataForm = $('#quote-form');
        dataForm.mage('validation', {});
    });
</script>